 
---

- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present
        
- name: Add Jenkins repository
  apt_repository:
      repo: deb http://pkg.jenkins.io/debian-stable binary/ 
      state: present

- name: Ensure Jenkins is Installed
  apt:
    name: jenkins
    update_cache: yes
    state: present

- name: Enable and Start the Jenkins Service
  service:
    name: jenkins
    enabled: yes
    state: started

- name: Allow all access to tcp port 80
  ufw:
    rule: allow
    port: '8080'
    proto: tcp
