---
- name: Include Ubuntu deploy
  include: install_Ubuntu.yaml
  when: ansible_os_family == 'Debian'

- name: Jenkins. Enable and restart
  service:
    name: jenkins
    state: restarted
    enabled: yes

    #- name: sleep for 30 seconds and continue with play
    #  wait_for:
    #    timeout: 30
    #  delegate_to: localhost


- name: init password jenkin
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: print init password jenkins
  debug:
    var: result.stdout
