$script = <<-SCRIPT 

apt update -yqq
apt install -yq git wget curl

SCRIPT





BOX_IMAGE = "generic/ubuntu1804"
NODE_COUNT = 3



Vagrant.configure("2") do |config|
    (1..NODE_COUNT).each do |i|
        config.vm.define "node#{i}" do |box|
            box.vm.box = BOX_IMAGE
            
            box.vm.hostname = "node#{i}"
            box.vm.network :private_network, ip: "192.168.200.#{i + 10}"

            box.vm.provision "shell", inline: $script    
        end
    end
end



