$script_for_router = <<-SCRIPT
echo 1 > /proc/sys/net/ipv4/ip_forward
echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
#Give node2 access to internet, but not node3
iptables -t nat -A POSTROUTING -s 192.168.20.12 -o eth0 -j MASQUERADE
SCRIPT


$script_for_hosts = <<-SCRIPT
route del default 
route add default gw 192.168.20.11 eth1
SCRIPT


BOX_IMAGE = "generic/ubuntu1804"
NODE_COUNT = 3



Vagrant.configure("2") do |config|
    (1..NODE_COUNT).each do |i|
        config.vm.define "node#{i}" do |box|
            box.vm.box = BOX_IMAGE
            
            box.vm.hostname = "node#{i}"
            box.vm.network :private_network, ip: "192.168.20.#{i + 10}"

            if i == 1
              # default router
              box.vm.provision "shell", inline: $script_for_router
            else
              box.vm.provision "shell", inline: $script_for_hosts
            end

        end
    end
end
